# Generated by Django 5.0 on 2026-04-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
    ]
