# Generated by Django 5.0 on 2026-04-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_email_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='important_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
