# Generated by Django 5.0 on 2026-04-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_email_important_text_alter_email_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='important_text',
        ),
    ]
